# Generated by Django 5.1.7 on 2025-05-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
